/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topdata.easyInner.ui;

import com.topdata.easyInner.controller.EasyInnerBioController6xx;
import com.topdata.easyInner.entity.UsuarioBio;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jonatas.silva
 */
public class JIFEasyInnerBio6xx extends javax.swing.JInternalFrame {

     //Declaração de variáveis
    private final EasyInnerBioController6xx bioController = new EasyInnerBioController6xx(this);
    
    /**
     * Creates new form JIFEasyInnerBio6xx
     */
    public JIFEasyInnerBio6xx() {
        initComponents();
        
        //Inicialização campos
        jTxtNumInner.setText("1");
        jTxtPorta.setText("3570");
        
        //Combo Padrão Cartão
        jCboTipoModuloBio.removeAllItems();
        jCboTipoModuloBio.addItem("Módulo LN");
        jCboTipoModuloBio.addItem("Módulo LC");
        jCboTipoModuloBio.setSelectedIndex(0);   //Default
        
        bioController.CarregarTemplatesBase();
    }
    
    public void AtualizarStatusBotoes(boolean b)
    {
        jbtnAtualizarUsuarios.setEnabled(b);
        jbtnEnviarTemplates.setEnabled(b);
        jbtnReceberTemplates.setEnabled(b);
        jbtnExcluirSelecionadosBase.setEnabled(b);
        jbtnExcluirSelecionadosInner.setEnabled(b);
        jbtnReceberQtdeUsuarios.setEnabled(b);
        jbtnExcluirTodosUsuarios.setEnabled(b);
    }
    
    private List<UsuarioBio> getUsuariosEnviar() {
        List<UsuarioBio> ListaUsuarioosEnviar = new ArrayList();
        int[] rows = jTblUsuariosBase.getSelectedRows();   
        for(int index = 0; index < rows.length; index++) {
            UsuarioBio user = new UsuarioBio();
            user.setCartao(jTblUsuariosBase.getValueAt(rows[index], 0).toString());
            user.setTemplate1(jTblUsuariosBase.getValueAt(rows[index], 1).toString());
            user.setTemplate2(jTblUsuariosBase.getValueAt(rows[index], 2).toString());
            ListaUsuarioosEnviar.add(user);
        }
        return ListaUsuarioosEnviar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbpBiometria = new javax.swing.JTabbedPane();
        tbConfiguracao = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnReceberModelo = new javax.swing.JButton();
        jBtnReceberVersao = new javax.swing.JButton();
        jTxtNumInner = new javax.swing.JTextField();
        jTxtPorta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlblTipoModuloBio = new javax.swing.JLabel();
        jCboTipoModuloBio = new javax.swing.JComboBox();
        chkHabVerificacao = new javax.swing.JCheckBox();
        chkHabIdentificacao = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cmdConfigurarIdentVerif = new javax.swing.JButton();
        jBtnEnviarAjustesBio = new javax.swing.JButton();
        jTxtTimeoutIdent = new javax.swing.JTextField();
        jTxtNivelLFD = new javax.swing.JTextField();
        jlblTimeouIndet = new javax.swing.JLabel();
        jlblNivelLFD = new javax.swing.JLabel();
        jchkDedoDuplicado = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        LblStatusConf = new javax.swing.JLabel();
        tbManutencaoUsuarioBio = new javax.swing.JDesktopPane();
        jPnlUsuariosInner = new javax.swing.JPanel();
        jbtnExcluirSelecionadosBase = new javax.swing.JButton();
        jbtnEnviarTemplates = new javax.swing.JButton();
        jScrUsuariosBase = new javax.swing.JScrollPane();
        jTblUsuariosBase = new javax.swing.JTable();
        jPnlUsuariosBase = new javax.swing.JPanel();
        jbtnReceberTemplates = new javax.swing.JButton();
        jbtnExcluirSelecionadosInner = new javax.swing.JButton();
        jScrUsuariosInner = new javax.swing.JScrollPane();
        jtblUsuariosInner = new javax.swing.JTable();
        jScrManutencao = new javax.swing.JScrollPane();
        jTxaManutencao = new javax.swing.JTextArea();
        jbtnReceberQtdeUsuarios = new javax.swing.JButton();
        jPnlQtdDigital = new javax.swing.JPanel();
        jRdbDigital1 = new javax.swing.JRadioButton();
        jRdbDigital2 = new javax.swing.JRadioButton();
        jbtnAtualizarUsuarios = new javax.swing.JButton();
        jbtnExcluirTodosUsuarios = new javax.swing.JButton();
        tbCadastroInner = new javax.swing.JPanel();
        jPnlCMDDiretoInnerBio = new javax.swing.JPanel();
        jLblUsuario = new javax.swing.JLabel();
        jTxtUsuarioCadInner = new javax.swing.JTextField();
        jBtnIdentificarUsuarioLeitor = new javax.swing.JButton();
        jbtnReceberTemplateLeitor = new javax.swing.JButton();
        jScrManutencao1 = new javax.swing.JScrollPane();
        jTxaCadastroInner = new javax.swing.JTextArea();
        jbtnVerificarCadastro = new javax.swing.JButton();
        jbtnVerificarDigital = new javax.swing.JButton();

        setTitle("Exemplo Bio 6xx");

        jTbpBiometria.setVerifyInputWhenFocusTarget(false);

        tbConfiguracao.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Número do inner:");

        jLabel5.setText("Porta:");

        jBtnReceberModelo.setText("Receber modelo bio");
        jBtnReceberModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceberModeloActionPerformed(evt);
            }
        });

        jBtnReceberVersao.setText("Receber versão bio");
        jBtnReceberVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceberVersaoActionPerformed(evt);
            }
        });

        jTxtNumInner.setText("1");

        jTxtPorta.setText("3570");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNumInner)
                    .addComponent(jTxtPorta, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnReceberVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReceberModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnReceberModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnReceberVersao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtNumInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblTipoModuloBio.setText("Tipo módulo bio:");

        jCboTipoModuloBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboTipoModuloBioActionPerformed(evt);
            }
        });

        chkHabVerificacao.setSelected(true);
        chkHabVerificacao.setText("Habilitar verificação biométrica");

        chkHabIdentificacao.setSelected(true);
        chkHabIdentificacao.setText("Habilitar identificação biométrica");

        jLabel1.setText("Biometria:");

        cmdConfigurarIdentVerif.setText("Configurar Identif e Verif");
        cmdConfigurarIdentVerif.setToolTipText("");
        cmdConfigurarIdentVerif.setPreferredSize(new java.awt.Dimension(127, 23));
        cmdConfigurarIdentVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfigurarIdentVerifActionPerformed(evt);
            }
        });

        jBtnEnviarAjustesBio.setText("Enviar Ajustes Bio");
        jBtnEnviarAjustesBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarAjustesBioActionPerformed(evt);
            }
        });

        jTxtTimeoutIdent.setText("70");

        jTxtNivelLFD.setText("0");

        jlblTimeouIndet.setText("Timeout Indet:");

        jlblNivelLFD.setText("Nivel LFD:");

        jchkDedoDuplicado.setSelected(true);
        jchkDedoDuplicado.setText("Dedo duplicado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlblTipoModuloBio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHabIdentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jCboTipoModuloBio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHabVerificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmdConfigurarIdentVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTimeouIndet)
                                    .addComponent(jlblNivelLFD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNivelLFD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxtTimeoutIdent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                            .addComponent(jBtnEnviarAjustesBio, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jchkDedoDuplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboTipoModuloBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTipoModuloBio))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(chkHabVerificacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkHabIdentificacao)
                                    .addComponent(jchkDedoDuplicado)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtTimeoutIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTimeouIndet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNivelLFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblNivelLFD))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnEnviarAjustesBio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdConfigurarIdentVerif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jlblTipoModuloBio.getAccessibleContext().setAccessibleName("Tipo módulo Bio");

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        LblStatusConf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblStatusConf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblStatusConf.setText("Selecione um comando.");
        LblStatusConf.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblStatusConf, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblStatusConf)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tbConfiguracao.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbConfiguracao.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbConfiguracao.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tbConfiguracaoLayout = new javax.swing.GroupLayout(tbConfiguracao);
        tbConfiguracao.setLayout(tbConfiguracaoLayout);
        tbConfiguracaoLayout.setHorizontalGroup(
            tbConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbConfiguracaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tbConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        tbConfiguracaoLayout.setVerticalGroup(
            tbConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbConfiguracaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTbpBiometria.addTab("Configurações", tbConfiguracao);

        tbManutencaoUsuarioBio.setBackground(new java.awt.Color(255, 255, 255));

        jPnlUsuariosInner.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitais na base de dados"));

        jbtnExcluirSelecionadosBase.setText("Excluir selecionados");
        jbtnExcluirSelecionadosBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirSelecionadosBaseActionPerformed(evt);
            }
        });

        jbtnEnviarTemplates.setText("Enviar templates >>");
        jbtnEnviarTemplates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarTemplatesActionPerformed(evt);
            }
        });

        jTblUsuariosBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cartão", "Template 1", "Template 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblUsuariosBase.getTableHeader().setReorderingAllowed(false);
        jScrUsuariosBase.setViewportView(jTblUsuariosBase);

        javax.swing.GroupLayout jPnlUsuariosInnerLayout = new javax.swing.GroupLayout(jPnlUsuariosInner);
        jPnlUsuariosInner.setLayout(jPnlUsuariosInnerLayout);
        jPnlUsuariosInnerLayout.setHorizontalGroup(
            jPnlUsuariosInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuariosInnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlUsuariosInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnExcluirSelecionadosBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEnviarTemplates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrUsuariosBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPnlUsuariosInnerLayout.setVerticalGroup(
            jPnlUsuariosInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuariosInnerLayout.createSequentialGroup()
                .addComponent(jScrUsuariosBase, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnEnviarTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExcluirSelecionadosBase, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlUsuariosBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitais no Inner"));

        jbtnReceberTemplates.setText("<< Receber templates");
        jbtnReceberTemplates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceberTemplatesActionPerformed(evt);
            }
        });

        jbtnExcluirSelecionadosInner.setText("Excluir selecionados");
        jbtnExcluirSelecionadosInner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirSelecionadosInnerActionPerformed(evt);
            }
        });

        jtblUsuariosInner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuarios"
            }
        ));
        jScrUsuariosInner.setViewportView(jtblUsuariosInner);

        javax.swing.GroupLayout jPnlUsuariosBaseLayout = new javax.swing.GroupLayout(jPnlUsuariosBase);
        jPnlUsuariosBase.setLayout(jPnlUsuariosBaseLayout);
        jPnlUsuariosBaseLayout.setHorizontalGroup(
            jPnlUsuariosBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlUsuariosBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlUsuariosBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnReceberTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jbtnExcluirSelecionadosInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
            .addGroup(jPnlUsuariosBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrUsuariosInner, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlUsuariosBaseLayout.setVerticalGroup(
            jPnlUsuariosBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlUsuariosBaseLayout.createSequentialGroup()
                .addComponent(jScrUsuariosInner, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReceberTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jbtnExcluirSelecionadosInner, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTxaManutencao.setBackground(new java.awt.Color(153, 255, 255));
        jTxaManutencao.setColumns(20);
        jTxaManutencao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTxaManutencao.setLineWrap(true);
        jTxaManutencao.setText("Selecione um comando");
        jTxaManutencao.setAutoscrolls(false);
        jScrManutencao.setViewportView(jTxaManutencao);

        jbtnReceberQtdeUsuarios.setText("Receber Quantidade Usuários Bio");
        jbtnReceberQtdeUsuarios.setActionCommand("Receber Quantidade de Usuários Bio");
        jbtnReceberQtdeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceberQtdeUsuariosActionPerformed(evt);
            }
        });

        jPnlQtdDigital.setBorder(javax.swing.BorderFactory.createTitledBorder("Inner Versão > 5.xx"));

        jRdbDigital1.setText("1 Digital");
        jRdbDigital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbDigital1ActionPerformed(evt);
            }
        });

        jRdbDigital2.setSelected(true);
        jRdbDigital2.setText("2 Digital");
        jRdbDigital2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbDigital2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlQtdDigitalLayout = new javax.swing.GroupLayout(jPnlQtdDigital);
        jPnlQtdDigital.setLayout(jPnlQtdDigitalLayout);
        jPnlQtdDigitalLayout.setHorizontalGroup(
            jPnlQtdDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlQtdDigitalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRdbDigital1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRdbDigital2)
                .addGap(26, 26, 26))
        );
        jPnlQtdDigitalLayout.setVerticalGroup(
            jPnlQtdDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlQtdDigitalLayout.createSequentialGroup()
                .addGroup(jPnlQtdDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbDigital2)
                    .addComponent(jRdbDigital1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jbtnAtualizarUsuarios.setText("Atualizar usuários");
        jbtnAtualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizarUsuariosActionPerformed(evt);
            }
        });

        jbtnExcluirTodosUsuarios.setText("Excluir todos usuários");
        jbtnExcluirTodosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirTodosUsuariosActionPerformed(evt);
            }
        });

        tbManutencaoUsuarioBio.setLayer(jPnlUsuariosInner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jPnlUsuariosBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jScrManutencao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jbtnReceberQtdeUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jPnlQtdDigital, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jbtnAtualizarUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbManutencaoUsuarioBio.setLayer(jbtnExcluirTodosUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tbManutencaoUsuarioBioLayout = new javax.swing.GroupLayout(tbManutencaoUsuarioBio);
        tbManutencaoUsuarioBio.setLayout(tbManutencaoUsuarioBioLayout);
        tbManutencaoUsuarioBioLayout.setHorizontalGroup(
            tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPnlQtdDigital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnReceberQtdeUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlUsuariosInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                        .addComponent(jbtnExcluirTodosUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAtualizarUsuarios))
                    .addComponent(jPnlUsuariosBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tbManutencaoUsuarioBioLayout.setVerticalGroup(
            tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                        .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnExcluirTodosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAtualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnlUsuariosBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tbManutencaoUsuarioBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(tbManutencaoUsuarioBioLayout.createSequentialGroup()
                                    .addComponent(jbtnReceberQtdeUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPnlQtdDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPnlUsuariosInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTbpBiometria.addTab("Manutenção Usuário Bio", tbManutencaoUsuarioBio);

        jPnlCMDDiretoInnerBio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblUsuario.setText("Usuário:");

        jBtnIdentificarUsuarioLeitor.setText("Identificar usuário pelo leitor");
        jBtnIdentificarUsuarioLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIdentificarUsuarioLeitorActionPerformed(evt);
            }
        });

        jbtnReceberTemplateLeitor.setText("Receber template pelo leitor");
        jbtnReceberTemplateLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceberTemplateLeitorActionPerformed(evt);
            }
        });

        jTxaCadastroInner.setBackground(new java.awt.Color(153, 255, 255));
        jTxaCadastroInner.setColumns(20);
        jTxaCadastroInner.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTxaCadastroInner.setLineWrap(true);
        jTxaCadastroInner.setText("Selecione um comando");
        jTxaCadastroInner.setAutoscrolls(false);
        jScrManutencao1.setViewportView(jTxaCadastroInner);

        jbtnVerificarCadastro.setText("Verificar cadastro");
        jbtnVerificarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerificarCadastroActionPerformed(evt);
            }
        });

        jbtnVerificarDigital.setText("Verificar digital");
        jbtnVerificarDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerificarDigitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlCMDDiretoInnerBioLayout = new javax.swing.GroupLayout(jPnlCMDDiretoInnerBio);
        jPnlCMDDiretoInnerBio.setLayout(jPnlCMDDiretoInnerBioLayout);
        jPnlCMDDiretoInnerBioLayout.setHorizontalGroup(
            jPnlCMDDiretoInnerBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCMDDiretoInnerBioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlCMDDiretoInnerBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnReceberTemplateLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnIdentificarUsuarioLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlCMDDiretoInnerBioLayout.createSequentialGroup()
                        .addComponent(jLblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtUsuarioCadInner))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCMDDiretoInnerBioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrManutencao1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlCMDDiretoInnerBioLayout.createSequentialGroup()
                        .addComponent(jbtnVerificarDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnVerificarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlCMDDiretoInnerBioLayout.setVerticalGroup(
            jPnlCMDDiretoInnerBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCMDDiretoInnerBioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrManutencao1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlCMDDiretoInnerBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUsuarioCadInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnIdentificarUsuarioLeitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnReceberTemplateLeitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlCMDDiretoInnerBioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnVerificarDigital)
                    .addComponent(jbtnVerificarCadastro))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tbCadastroInnerLayout = new javax.swing.GroupLayout(tbCadastroInner);
        tbCadastroInner.setLayout(tbCadastroInnerLayout);
        tbCadastroInnerLayout.setHorizontalGroup(
            tbCadastroInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbCadastroInnerLayout.createSequentialGroup()
                .addComponent(jPnlCMDDiretoInnerBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 574, Short.MAX_VALUE))
        );
        tbCadastroInnerLayout.setVerticalGroup(
            tbCadastroInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbCadastroInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlCMDDiretoInnerBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTbpBiometria.addTab("Cadastro Leitor Inner", tbCadastroInner);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbpBiometria)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbpBiometria, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReceberTemplateLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceberTemplateLeitorActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //Mensagem de Status
                    bioController.ReceberTemplateLeitor();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        }).start();
    }//GEN-LAST:event_jbtnReceberTemplateLeitorActionPerformed

    private void jBtnIdentificarUsuarioLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIdentificarUsuarioLeitorActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //Mensagem de Status
                    bioController.IdentificarDigital();
                    //Obrigatório
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }).start();
    }//GEN-LAST:event_jBtnIdentificarUsuarioLeitorActionPerformed

    private void jbtnAtualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizarUsuariosActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                AtualizarStatusBotoes(false);
                try {
                    bioController.AtualizarListaUsuarios();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                AtualizarStatusBotoes(true);
                try {
                    
                } catch (Exception ex) {
                    Logger.getLogger(JIFEasyInnerBio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jbtnAtualizarUsuariosActionPerformed

    private void jRdbDigital2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbDigital2ActionPerformed
        jRdbDigital1.setSelected(!jRdbDigital2.isSelected());
    }//GEN-LAST:event_jRdbDigital2ActionPerformed

    private void jRdbDigital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbDigital1ActionPerformed
        jRdbDigital2.setSelected(!jRdbDigital1.isSelected());
    }//GEN-LAST:event_jRdbDigital1ActionPerformed

    private void jbtnReceberQtdeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceberQtdeUsuariosActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                AtualizarStatusBotoes(false);
                try {
                    bioController.ReceberQtdUsuariosBio();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                AtualizarStatusBotoes(true);
            }
        }).start();
    }//GEN-LAST:event_jbtnReceberQtdeUsuariosActionPerformed

    private void jbtnExcluirSelecionadosInnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirSelecionadosInnerActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                AtualizarStatusBotoes(false);
                try {
                    bioController.ExcluirUsuarioBioInner();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                AtualizarStatusBotoes(true);
            }
        }).start();
    }//GEN-LAST:event_jbtnExcluirSelecionadosInnerActionPerformed

    private void jbtnReceberTemplatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceberTemplatesActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try
                {
                    AtualizarStatusBotoes(false);
                    bioController.ReceberDigitaisBio();
                    AtualizarStatusBotoes(true);
                }
                catch (Exception ex)
                {
                    Logger.getLogger(JIFEasyInnerBio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jbtnReceberTemplatesActionPerformed

    private void jbtnEnviarTemplatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarTemplatesActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                AtualizarStatusBotoes(false);
                List<UsuarioBio> ListaUsuariosEnviar = getUsuariosEnviar();
                try {
                    bioController.EnviarDigitaisInner(ListaUsuariosEnviar);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                AtualizarStatusBotoes(true);
            }
        }).start();
    }//GEN-LAST:event_jbtnEnviarTemplatesActionPerformed

    private void jbtnExcluirSelecionadosBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirSelecionadosBaseActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                Thread.currentThread().setName("EnviarUsuarioSelecionado");
                AtualizarStatusBotoes(false);
                bioController.ExcluirUsuarioBD();
                AtualizarStatusBotoes(true);
            }
        }).start();
    }//GEN-LAST:event_jbtnExcluirSelecionadosBaseActionPerformed

    private void jBtnEnviarAjustesBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarAjustesBioActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                jTxaManutencao.append("Enviando Ajustes Bio...");
                try {
                    bioController.EnviarAjustesBio();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jBtnEnviarAjustesBioActionPerformed

    private void cmdConfigurarIdentVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfigurarIdentVerifActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    bioController.ConfigurarIdentificacaoVerificacao();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }).start();
    }//GEN-LAST:event_cmdConfigurarIdentVerifActionPerformed

    private void jBtnReceberVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceberVersaoActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    bioController.ReceberVersaoBio();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jBtnReceberVersaoActionPerformed

    private void jBtnReceberModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceberModeloActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    bioController.ReceberModeloBio();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jBtnReceberModeloActionPerformed

    private void jbtnExcluirTodosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirTodosUsuariosActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                AtualizarStatusBotoes(false);
                try {
                    bioController.ExcluirTodosUsuariosInner();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
                AtualizarStatusBotoes(true);
            }
        }).start();
    }//GEN-LAST:event_jbtnExcluirTodosUsuariosActionPerformed

    private void jbtnVerificarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerificarCadastroActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {

                try {
                    bioController.VerificarCadastro();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }).start(); 
    }//GEN-LAST:event_jbtnVerificarCadastroActionPerformed

    private void jbtnVerificarDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerificarDigitalActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {

                try {
                    bioController.VerificarDigital();
                } catch (InterruptedException ex) {
                    Logger.getLogger(JIFEasyInnerBio6xx.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jbtnVerificarDigitalActionPerformed

    private void jCboTipoModuloBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboTipoModuloBioActionPerformed
        bioController.CarregarTemplatesBase();
        if (jCboTipoModuloBio.getSelectedIndex() == 0)
        {        
            jTxtTimeoutIdent.setText("70");
            jlblNivelLFD.setText("Nivel LFD");
            jTxtNivelLFD.setText("0");
            jchkDedoDuplicado.setSelected(false);
            jchkDedoDuplicado.setVisible(false);
        }else{
            jTxtTimeoutIdent.setText("5");
            jlblNivelLFD.setText("Segurança Ident.:");
            jTxtNivelLFD.setText("3");
            jchkDedoDuplicado.setVisible(true);
            jchkDedoDuplicado.setSelected(true);
        }
    }//GEN-LAST:event_jCboTipoModuloBioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LblStatusConf;
    public javax.swing.JCheckBox chkHabIdentificacao;
    public javax.swing.JCheckBox chkHabVerificacao;
    public javax.swing.JButton cmdConfigurarIdentVerif;
    public javax.swing.JButton jBtnEnviarAjustesBio;
    private javax.swing.JButton jBtnIdentificarUsuarioLeitor;
    public javax.swing.JButton jBtnReceberModelo;
    public javax.swing.JButton jBtnReceberVersao;
    public javax.swing.JComboBox jCboTipoModuloBio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnlCMDDiretoInnerBio;
    private javax.swing.JPanel jPnlQtdDigital;
    private javax.swing.JPanel jPnlUsuariosBase;
    private javax.swing.JPanel jPnlUsuariosInner;
    public javax.swing.JRadioButton jRdbDigital1;
    public javax.swing.JRadioButton jRdbDigital2;
    private javax.swing.JScrollPane jScrManutencao;
    private javax.swing.JScrollPane jScrManutencao1;
    private javax.swing.JScrollPane jScrUsuariosBase;
    private javax.swing.JScrollPane jScrUsuariosInner;
    public javax.swing.JTable jTblUsuariosBase;
    public javax.swing.JTabbedPane jTbpBiometria;
    public javax.swing.JTextArea jTxaCadastroInner;
    public javax.swing.JTextArea jTxaManutencao;
    public javax.swing.JTextField jTxtNivelLFD;
    public javax.swing.JTextField jTxtNumInner;
    public javax.swing.JTextField jTxtPorta;
    public javax.swing.JTextField jTxtTimeoutIdent;
    public javax.swing.JTextField jTxtUsuarioCadInner;
    private javax.swing.JButton jbtnAtualizarUsuarios;
    private javax.swing.JButton jbtnEnviarTemplates;
    private javax.swing.JButton jbtnExcluirSelecionadosBase;
    private javax.swing.JButton jbtnExcluirSelecionadosInner;
    private javax.swing.JButton jbtnExcluirTodosUsuarios;
    private javax.swing.JButton jbtnReceberQtdeUsuarios;
    private javax.swing.JButton jbtnReceberTemplateLeitor;
    private javax.swing.JButton jbtnReceberTemplates;
    private javax.swing.JButton jbtnVerificarCadastro;
    private javax.swing.JButton jbtnVerificarDigital;
    public javax.swing.JCheckBox jchkDedoDuplicado;
    private javax.swing.JLabel jlblNivelLFD;
    private javax.swing.JLabel jlblTimeouIndet;
    private javax.swing.JLabel jlblTipoModuloBio;
    public javax.swing.JTable jtblUsuariosInner;
    private javax.swing.JPanel tbCadastroInner;
    private javax.swing.JDesktopPane tbConfiguracao;
    private javax.swing.JDesktopPane tbManutencaoUsuarioBio;
    // End of variables declaration//GEN-END:variables
}
